### ISSUE TITLE
Vise personlig mål for antall skritt

### ISSUE THREAD

**Issue by MiriamFi** [IT2810/it2810-webutvikling-h18-prosjekt-3-03#16]
Avhengig av #13.

- [x] I StepInfoComponent skal det vises det personlige målet for i dag.
- [ ] I StepLogComponent skal det vises det personlige målet for valgt dato.

**Comment by Katrinhh** [comment]
Løses ved at det er lagt inn et generelt mål for hver dag. Viser hvor langt man har kommet i forhold til dette. Har gått bort fra å vise personlig mål for valgt dato.
