### ISSUE TITLE
Lage StepLog sine listeelementer

### ISSUE THREAD

**Issue by MiriamFi** [IT2810/it2810-webutvikling-h18-prosjekt-3-03#25]
Avhengig av #24.
Et liste element skal vise
- [x] Dato
- [x] Antall skritt
- [x] Mål for den datoen
- [x] Om målet ble oppnådd (gjerne ikon)

Dette er bare listeoppsettet; den kan vise test data.

**Comment by Katrinhh** [comment]
Løses ved å lage en liste som har listeelementer hvor antall skritt man har gått i forhold til mål vises og dato, i tillegg til et lite stjerneikon hvis målet er oppnådd.
